http:
  routers:
    exterior-quote-assistant:
      rule: "Host(`sentinelforge.tech`) && PathPrefix(`/quote-system`)"
      priority: 1002
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: exterior-quote-assistant

  services:
    exterior-quote-assistant:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:8501"
